refactor for readability and maintainability

diff --git a/spoon b/spoon
--- a/spoon
+++ b/spoon
@@ -1,7 +1,40 @@
 #!/usr/bin/env bash
 
+spoon_usage_and_help() {
+	if [[ $# -lt 1 ]]; then
+		print_help
+		exit 1
+	fi
+
+	if has_short_flag h "$@" || has_long_flag help "$@"; then
+		print_help
+		exit 0
+	fi
+}
+
 print_help() {
 	echo "usage: spoon [flags] <identifier>"
+}
+
+################################################################################################
+################################################################################################
+
+spoon_set_args() {
+	identifier="${*: -1}"
+
+	if [[ "${identifier}" =~ ^- ]]; then
+		echo identifier must not be empty
+		exit 1
+	fi
+
+	if has_short_flag i "$@" || has_long_flag instance-id "$@"; then arg_instance_id=1; else arg_instance_id=0; fi
+	if has_short_flag p "$@" || has_long_flag preprod "$@"; then arg_preprod=1; else arg_preprod=0; fi
+	if has_short_flag P "$@" || has_long_flag prod "$@"; then arg_prod=1; else arg_prod=0; fi
+	if has_short_flag 1 "$@" || has_long_flag first "$@"; then arg_first=1; else arg_first=0; fi
+	if has_short_flag a "$@" || has_long_flag all "$@"; then arg_all=1; else arg_all=0; fi
+	if has_short_flag n "$@" || has_long_flag dry-run "$@"; then arg_dry_run=1; else arg_dry_run=0; fi
+	if has_short_flag v "$@" || has_long_flag verbose "$@"; then arg_verbose=1; else arg_verbose=0; fi
+	if has_short_flag V "$@"; then arg_verbose=1 && arg_verybose=1; else arg_verybose=0; fi
 }
 
 has_short_flag() {
@@ -28,7 +61,7 @@ has_long_flag() {
 	return 1
 }
 
-check_args() {
+spoon_check_args() {
 	if [[ "${arg_prod}" = 1 ]] && [[ "${arg_preprod}" = 1 ]]; then
 		echo "Invalid arguments: -P/--prod and -p/--preprod are mutually exclusive."
 		exit 1
@@ -39,8 +72,42 @@ check_args() {
 	fi
 }
 
+spoon_verbose_print_args() {
+	if [[ "${arg_verbose}" = 1 ]]; then
+		echo "[spoon] identifier=${identifier}"
+		echo "[spoon] arg_instance_id=${arg_instance_id}"
+		echo "[spoon] arg_preprod=${arg_preprod}"
+		echo "[spoon] arg_prod=${arg_prod}"
+		echo "[spoon] arg_first=${arg_first}"
+		echo "[spoon] arg_dry_run=${arg_dry_run}"
+	fi
+}
+
 ################################################################################################
 ################################################################################################
+
+spoon_get_instances_from_aws() {
+	if [[ $arg_instance_id = 1 ]]; then
+		nodes=$(query_aws_by_id "$identifier")
+	else
+		nodes=$(query_aws_by_name "$identifier")
+	fi
+	# I don't want to cram the entire if statement into the condition of another one
+	# shellcheck disable=SC2181
+	if [[ "$?" -ne 0 ]]; then
+		echo "Encountered an error while using awscli. Please make sure it's installed and you are authorized to make requests."
+		exit 1
+	fi
+
+	nodes="$(echo "${nodes}" | jq 'sort_by(.service)')"
+	[[ "${arg_verybose}" = 1 ]] && echo -e "[spoon] instances returned from aws:\\n${nodes}"
+
+	node_count=$(echo "${nodes}" | jq '. | length')
+	if [[ "${node_count}" -eq 0 ]]; then
+		echo "No instances found for identifier '${identifier}'."
+		exit 1
+	fi
+}
 
 query_aws() {
 	[[ "${arg_verbose}" = 1 ]] && echo "[spoon] querying aws..."
@@ -65,8 +132,85 @@ query_aws_by_id() {
 ################################################################################################
 ################################################################################################
 
+spoon_filter_for_environment() {
+	if [[ $arg_preprod = 1 ]]; then
+		nodes=$(echo "${nodes}" | jq 'map(select(.service | test("preprod|-pp")))')
+		[[ "${arg_verbose}" = 1 ]] && echo "[spoon] nodes after filtering for preprod: ${nodes}"
+		node_count=$(echo "${nodes}" | jq '. | length')
+		if [[ "${node_count}" -eq 0 ]]; then
+			echo "No instances found for identifier '${identifier}' after filtering for preprod."
+			exit 1
+		fi
+	elif [[ $arg_prod = 1 ]]; then
+		nodes=$(echo "${nodes}" | jq 'map(select(.service | test("preprod|-pp") | not))')
+		[[ "${arg_verbose}" = 1 ]] && echo "[spoon] nodes after filtering for prod: ${nodes}"
+		node_count=$(echo "${nodes}" | jq '. | length')
+		if [[ "${node_count}" -eq 0 ]]; then
+			echo "No instances found for identifier '${identifier}' after filtering for prod."
+			exit 1
+		fi
+	fi
+}
+
+spoon_filter_for_first() {
+	if [[ $arg_first = 1 ]]; then
+		nodes=$(echo "${nodes}" | jq '[.[0]]')
+		[[ "${arg_verbose}" = 1 ]] && echo -e "[spoon] first instance selected:\\n${nodes}"
+		node_count=1
+	fi
+}
+
+spoon_select_from_multiple() {
+	if [[ $arg_all = 0 ]] && [[ $node_count -gt 1 ]]; then
+		nodes_data="$(echo "${nodes}" | jq '.[] | .id + " " + .service + " " + .ip + " (" + .state + ")"' | tr -d '\"')"
+		echo "${nodes_data}"| nl '-s) ' | column -t
+		echo "*)  all"
+		read -rp '==> ' reply
+		if [[ "${reply}" = "" ]]; then
+			[[ "${arg_verbose}" = 1 ]] && echo "[spoon] no instances selected; spoon will now exit."
+			exit 0
+		fi
+		if [[ "${reply}" = '*' ]]; then
+			[[ "${arg_verbose}" = 1 ]] && echo all instances selected
+		else
+			jq_range_expression="$(jqrangify "${reply}")"
+			[[ "${arg_verybose}" = 1 ]] && echo "[spoon] jq range expression: ${jq_range_expression}"
+			if ! nodes="$(echo "${nodes}" | jq "${jq_range_expression}" 2>/dev/null)"; then
+				echo "[spoon] jq error: invalid selector"
+				exit 1
+			fi
+			node_count=$(echo "${nodes}" | jq '. | length')
+			if [[ "${node_count}" -eq 0 ]]; then
+				echo "[spoon] no instances selected; spoon will now exit."
+				exit 0
+			fi
+			[[ "${arg_verybose}" = 1 ]] && echo -e "[spoon] selected instances:\\n${nodes}"
+		fi
+	fi
+}
+
+jqrangify() {
+	# The easiest way I found to select multiple items, including ranges, from the array
+	# is converting all indices to jq range expressions to extract subarrays
+	# and adding these all together.
+	# e.g '1, 3, 5-10' --> jq '.[0:1] + .[2:3] + .[4:10]'
+	expr=""
+	for item in $(echo "${*}" | tr , ' '); do
+		# note: for single numbers 'lower' and 'upper' end up being the same
+		lower="${item//-*/}"
+		upper="${item//*-/}"
+		# arrays are 0-indexed, spoon numbers instances from 1, hence the substraction
+		jqrangified_item="$((lower - 1)):${upper}"
+		expr="${expr} .[${jqrangified_item}] +"
+	done
+	# append [] at the end to deal with the trailing + sign
+	echo "${expr} []"
+}
+
+################################################################################################
+################################################################################################
+
 spoon_ssh() {
-	nodes="$1"
 	node_count=$(echo "${nodes}" | jq '. | length')
 	[[ "${arg_verbose}" = 1 ]] && echo "[spoon] number of instances: ${node_count}"
 	if [[ "${node_count}" -gt 1 ]]; then
@@ -120,137 +264,18 @@ check_cssh_availability() {
 }
 
 ################################################################################################
-################################################################################################
-
-jqrangify() {
-	# The easiest way I found to select multiple items, including ranges, from the array
-	# is converting all indices to jq range expressions to extract subarrays
-	# and adding these all together.
-	# e.g '1, 3, 5-10' --> jq '.[0:1] + .[2:3] + .[4:10]'
-	expr=""
-	for item in $(echo "${*}" | tr , ' '); do
-		# note: for single numbers 'lower' and 'upper' end up being the same
-		lower="${item//-*/}"
-		upper="${item//*-/}"
-		# arrays are 0-indexed, spoon numbers instances from 1, hence the substraction
-		jqrangified_item="$((lower - 1)):${upper}"
-		expr="${expr} .[${jqrangified_item}] +"
-	done
-	# append [] at the end to deal with the trailing + sign
-	echo "${expr} []"
-}
-
-################################################################################################
 ### execution starts here
 ################################################################################################
 
-if [[ $# -lt 1 ]]; then
-	print_help
-	exit 1
-fi
+spoon_usage_and_help "${@}"
 
-if has_short_flag h "$@" || has_long_flag help "$@"; then
-	print_help
-	exit 0
-fi
+spoon_set_args "${@}"
+spoon_check_args
+spoon_verbose_print_args
 
-identifier="${*: -1}"
+spoon_get_instances_from_aws
+spoon_filter_for_environment
+spoon_filter_for_first
+spoon_select_from_multiple
 
-if [[ "${identifier}" =~ ^- ]]; then
-	echo identifier must not be empty
-	exit 1
-fi
-
-if has_short_flag i "$@" || has_long_flag instance-id "$@"; then arg_instance_id=1; else arg_instance_id=0; fi
-if has_short_flag p "$@" || has_long_flag preprod "$@"; then arg_preprod=1; else arg_preprod=0; fi
-if has_short_flag P "$@" || has_long_flag prod "$@"; then arg_prod=1; else arg_prod=0; fi
-if has_short_flag 1 "$@" || has_long_flag first "$@"; then arg_first=1; else arg_first=0; fi
-if has_short_flag a "$@" || has_long_flag all "$@"; then arg_all=1; else arg_all=0; fi
-if has_short_flag n "$@" || has_long_flag dry-run "$@"; then arg_dry_run=1; else arg_dry_run=0; fi
-if has_short_flag v "$@" || has_long_flag verbose "$@"; then arg_verbose=1; else arg_verbose=0; fi
-if has_short_flag V "$@"; then arg_verbose=1 && arg_verybose=1; else arg_verybose=0; fi
-
-check_args
-
-if [[ "${arg_verbose}" = 1 ]]; then
-	echo "[spoon] identifier=${identifier}"
-	echo "[spoon] arg_instance_id=${arg_instance_id}"
-	echo "[spoon] arg_preprod=${arg_preprod}"
-	echo "[spoon] arg_prod=${arg_prod}"
-	echo "[spoon] arg_first=${arg_first}"
-	echo "[spoon] arg_dry_run=${arg_dry_run}"
-fi
-
-if [[ $arg_instance_id = 1 ]]; then
-	nodes=$(query_aws_by_id "$identifier")
-else
-	nodes=$(query_aws_by_name "$identifier")
-fi
-# I don't want to cram the entire if statement into the condition of another one
-# shellcheck disable=SC2181
-if [[ "$?" -ne 0 ]]; then
-	echo "Encountered an error while using awscli. Please make sure it's installed and you are authorized to make requests."
-	exit 1
-fi
-
-nodes="$(echo "${nodes}" | jq 'sort_by(.service)')"
-[[ "${arg_verybose}" = 1 ]] && echo -e "[spoon] instances returned from aws:\\n${nodes}"
-
-node_count=$(echo "${nodes}" | jq '. | length')
-if [[ "${node_count}" -eq 0 ]]; then
-	echo "No instances found for identifier '${identifier}'."
-	exit 1
-fi
-
-if [[ $arg_preprod = 1 ]]; then
-	nodes=$(echo "${nodes}" | jq 'map(select(.service | test("preprod|-pp")))')
-	[[ "${arg_verbose}" = 1 ]] && echo "[spoon] nodes after filtering for preprod: ${nodes}"
-	node_count=$(echo "${nodes}" | jq '. | length')
-	if [[ "${node_count}" -eq 0 ]]; then
-		echo "No instances found for identifier '${identifier}' after filtering for preprod."
-		exit 1
-	fi
-elif [[ $arg_prod = 1 ]]; then
-	nodes=$(echo "${nodes}" | jq 'map(select(.service | test("preprod|-pp") | not))')
-	[[ "${arg_verbose}" = 1 ]] && echo "[spoon] nodes after filtering for prod: ${nodes}"
-	node_count=$(echo "${nodes}" | jq '. | length')
-	if [[ "${node_count}" -eq 0 ]]; then
-		echo "No instances found for identifier '${identifier}' after filtering for prod."
-		exit 1
-	fi
-fi
-
-if [[ $arg_first = 1 ]]; then
-	nodes=$(echo "${nodes}" | jq '[.[0]]')
-	[[ "${arg_verbose}" = 1 ]] && echo -e "[spoon] first instance selected:\\n${nodes}"
-	node_count=1
-fi
-
-if [[ $arg_all = 0 ]] && [[ $node_count -gt 1 ]]; then
-	nodes_data="$(echo "${nodes}" | jq '.[] | .id + " " + .service + " " + .ip + " (" + .state + ")"' | tr -d '\"')"
-	echo "${nodes_data}"| nl '-s) ' | column -t
-	echo "*)  all"
-	read -rp '==> ' reply
-	if [[ "${reply}" = "" ]]; then
-		[[ "${arg_verbose}" = 1 ]] && echo "[spoon] no instances selected; spoon will now exit."
-		exit 0
-	fi
-	if [[ "${reply}" = '*' ]]; then
-		[[ "${arg_verbose}" = 1 ]] && echo all instances selected
-	else
-		jq_range_expression="$(jqrangify "${reply}")"
-		[[ "${arg_verybose}" = 1 ]] && echo "[spoon] jq range expression: ${jq_range_expression}"
-		if ! nodes="$(echo "${nodes}" | jq "${jq_range_expression}" 2>/dev/null)"; then
-			echo "[spoon] jq error: invalid selector"
-			exit 1
-		fi
-		node_count=$(echo "${nodes}" | jq '. | length')
-		if [[ "${node_count}" -eq 0 ]]; then
-			echo "[spoon] no instances selected; spoon will now exit."
-			exit 0
-		fi
-		[[ "${arg_verybose}" = 1 ]] && echo -e "[spoon] selected instances:\\n${nodes}"
-	fi
-fi
-
-spoon_ssh "${nodes}"
+spoon_ssh
